### ISSUE TITLE
Custom navbar-collapse flex property is pushing navbar content to the right.

### ISSUE THREAD

**Issue by papegaill** [coliff/bootstrap-ie11#17]
Hi,

First of all, thanks for the script! By testing it on ie11, I realize that the flex property applied to the `.navbar-collapse` element pushes the contents of the navbar too far to the right and this creates horizontal scrollbars.

![ie-11-navbar-flex](https://user-images.githubusercontent.com/1289480/95255590-ec84c800-0821-11eb-8516-9b4f2c36cd36.png)

`.navbar-collapse {
  flex: 1 0 100%;
}
`

I think this property should be removed.

**Comment by coliff** [comment]
I've just released alpha2 with this fix!
https://github.com/coliff/bootstrap-ie11/releases

**Comment by papegaill** [comment]
@coliff Many thks for the new release!
