### ISSUE TITLE
polyfill.io new ownership

### ISSUE THREAD

**Issue by tpatartmajeur** [coliff/bootstrap-ie11#249]
### Prerequisites

- [X] I have [searched](https://github.com/coliff/bootstrap-ie11/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have validated any HTML to avoid common problems

### Describe the issue

There has been a recent development around polyfill.io which is used in this project

Polyfill.io has recently been transferred to a Chinese company called Funnull, which means that the hosting of the service has probably been moved out of the UK and EU.

There's an active thread about it here: https://github.com/polyfillpolyfill/polyfill-service/issues/2834

Alternatively, there's https://polyfill-fastly.io/

https://polyfill-fastly.io/v3/polyfill.min.js?features=default%2CNumber.parseInt%2CNumber.parseFloat%2CArray.prototype.find%2CArray.prototype.includes

### What version of Bootstrap are you using?

5.2.0

**Comment by coliff** [comment]
hey - thanks for the heads-up on this!

**Comment by y377** [comment]
@coliff 

https://twitter.com/CatChen/status/1811996989112102952

Please note this

**Comment by coliff** [comment]
> @coliff
> 
> [twitter.com/CatChen/status/1811996989112102952](https://twitter.com/CatChen/status/1811996989112102952)
> 
> Please note this

Thanks - noted. We removed all links to polyfill.io
