### ISSUE TITLE
Figure with .img-fluid is not resized

### ISSUE THREAD

**Issue by Re-Fish** [coliff/bootstrap-ie11#52]
"The fluid image in a figure container is not resized at all making it overflow the content area".
I've met this and found that it is a known issue [here](https://github.com/twbs/bootstrap/issues/25242). The solution is just to add this code to your css-file:
```css
figure .img-fluid {
    width: 100%;
}
```
May be it could be solved somehow in the future.

![img-fluid broken](https://user-images.githubusercontent.com/52908547/110438350-17788e00-80d8-11eb-908f-4d7d6f6209e9.png)
![img-fluid fixed](https://user-images.githubusercontent.com/52908547/110438355-19425180-80d8-11eb-9cd9-e74578ed1fe7.png)

**Comment by coliff** [comment]
Heya. Thanks for reporting this issue. I can reproduce the issue - though it's unfortunately not as simple as adding:
```css
figure .img-fluid {
    width: 100%;
}
```
because the above can break the correct sizing of SVG images. I'll take a deeper look into this tomorrow, but for now I've added a figures section to the demo page.
https://coliff.github.io/bootstrap-ie11/tests/#figures

**Comment by Re-Fish** [comment]
Also I've noticed next behavior:
if there is no "max-width" specified for <figure> in CSS and an image has bigger width than the area containing this image then this image is overflowing that area. If we specify "max-width" for <figure> then we can see that this image looks OK but the area containing this image behaves like this image is shown fullsize.
![without max-width](https://user-images.githubusercontent.com/52908547/111122297-acbfca80-858f-11eb-872a-787d989b32e9.png)
![with max-width](https://user-images.githubusercontent.com/52908547/111122295-ab8e9d80-858f-11eb-86e1-5dd181a4e709.png)

**Comment by coliff** [comment]
I don't think there is a single CSS fix we can add which would work in all cases. Sometimes specifying the `width` and `height` attributes on the image will be enough, other times you'll need to add `width: 100%;` CSS. 

Let me know if you have any other suggestions, but for now I think we should just document this potential issue in the README and demo.
