### ISSUE TITLE
Modal Bootstrap 5 is not working

### ISSUE THREAD

**Issue by ltrtuan** [coliff/bootstrap-ie11#88]
Hi
I use https://cdn.jsdelivr.net/combine/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js but there is a error in my project
Uncaught TypeError: bootstrap.Modal.getOrCreateInstance is not a function
and
Object doesn't support property or method 'closest'

**Comment by coliff** [comment]
Heya. The modal is working here: https://coliff.github.io/bootstrap-ie11/tests/#modal
Can you please test and see if you can resolve the issue by looking at that code. Make sure you have all the Polyfills as documented.

**Comment by ltrtuan** [comment]
Thanks for replying
This is my screenshot http://prntscr.com/1pslcx1. IE version 21H1 is 11 ?

**Comment by coliff** [comment]
Yes, that's IE11. Does the modal work on my test page?

It works on IE11 on my Windows 10 (though I have a slightly older version):
![image](https://user-images.githubusercontent.com/1212885/129592969-0740b9b0-0be3-4687-b934-0af521b44a33.png)

**Comment by ltrtuan** [comment]
No it not.  i showe you the error in bootstrap.bundle.min.js
![image](https://user-images.githubusercontent.com/4776640/129593417-2d1cc0a6-f230-4cc9-8e16-63dc551c75d5.png)

**Comment by coliff** [comment]
I'll take a look into it tomorrow - it's working here though:
![image](https://user-images.githubusercontent.com/1212885/129593673-d247e0a0-0745-4f7c-9a53-7f14ae208aba.png)
The syntax error in console is normal, but all components JS should work (except Offcanvas)

**Comment by ltrtuan** [comment]
Sorry, it works. I thought it is not working because of the error. Thanks for your support

**Comment by ltrtuan** [comment]
But i have error in Chrome
This is my code
var myModalEl = document.querySelectorAll('#modal-video');
	myModalEl.forEach(function(element){
		if (typeof(element) != 'undefined' && element != null){
			var modal = bootstrap.Modal.getOrCreateInstance(element);
			modal.show();
		}
	});
The error is Uncaught TypeError: bootstrap.Modal.getOrCreateInstance is not a function 
If i use original bootstrap.js it works
